# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Logger-iphone' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    use_modular_headers!
    # Pods for Logger
#    pod 'Log',:path => '../Modules/Log/'
    pod 'ALLiveLogger',:path => '../Modules/ALLiveLogger/'
    pod 'XCGLogger'
    pod 'CocoaLumberjack'
end
